# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build hwchoc nice_nano_v2'
on:
  push:
    branches:
      - '**'
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["hwchoc_left","hwchoc_right"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '["evgnskv/miryoku_zmk/hwchoc-custom-layers","zmkfirmware/zmk/main evgnskv/miryoku_zmk/hwchoc-custom-layers"]'